- hosts: kubernetes-worker-nodes
  become: yes
  become_user: root
  vars_files:
    - env_variables
  tasks:
    - name: Get join command from master
      shell: kubeadm token create --print-join-command
      register: join_command_output
      changed_when: false

    - name: Extract join command
      set_fact:
        join_command: "{{ join_command_output.stdout_lines[0] }}"
      changed_when: false

    - name: Run kubeadm join command on worker nodes
      command: "{{ join_command }}"
      when: "'worker0' in inventory_hostname or 'worker1' in inventory_hostname"

