---
- hosts: kubernetes-master-nodes
  become: yes
  vars_files:
  - env_variables 
  tasks:
  - name: Pulling images required for setting up a Kubernetes cluster
    shell: kubeadm config images pull


  - name: Initializing Kubernetes cluster
    shell: sudo kubeadm init --v=5 --upload-certs --control-plane-endpoint master:6443 --pod-network-cidr=192.168.0.0/16
    register: output

  - name: Copying required files
    shell: |
     modprobe overlay
     modprobe br_netfilter
     rm /etc/containerd/config.toml
     systemctl restart containerd
     export KUBECONFIG=/etc/kubernetes/admin.conf

  - name: Create .kube directory
    command: mkdir -p /home/azureuser/.kube

  - name: Copy admin.conf to .kube/config
    command: sudo cp -i /etc/kubernetes/admin.conf /home/azureuser/.kube/config

  - name: Set ownership of .kube/config
    file:
      path: /home/azureuser/.kube/config
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      state: file

  - name: Storing Logs and Generated token for future purpose.
    local_action: copy content={{ output.stdout }} dest={{ token_file }}

  - name: Install Network Add-on
    command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

