- hosts: kubernetes-worker-nodes
  become: yes
  become_user: azureuser
  vars_files:
    - env_variables
  tasks:
    - name: Copy token to worker nodes
      copy:
        src: "{{ token_file }}"
        dest: join_token
        mode: '0777'

    - name: Join worker1 nodes with Kubernetes master
      shell: "sudo sh join_token"
      register: join_command      
      when: "'worker0' in inventory_hostname"

    - name: Join worker1 nodes with Kubernetes master
      shell: "sudo sh join_token"
      register: join_command
      when: "'worker1' in inventory_hostname"
